rootProject.name = "GsonBooster"

include(":booster-annotation")
include(":kapt-demo")
include(":ksp-demo")
include(":benchmark")
include(":base:processor-base")
include(":base:scan:scan-kapt")
include(":base:scan:scan-ksp")
include(":booster-processor:processor-kapt")
include(":booster-processor:processor-ksp")
include(":base:processor-base-test")
include(":base:gen")
include(":base:check")
include(":base:contract")
